version: 2.1

jobs:
  build:
    docker:
      - image: cimg/elixir:1.14
    steps:
      - checkout
      - run: mix --version
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
